/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { ShortcutService } from "../shortcut.service";
import { ShortcutCreateInput } from "./ShortcutCreateInput";
import { Shortcut } from "./Shortcut";
import { ShortcutFindManyArgs } from "./ShortcutFindManyArgs";
import { ShortcutWhereUniqueInput } from "./ShortcutWhereUniqueInput";
import { ShortcutUpdateInput } from "./ShortcutUpdateInput";

export class ShortcutControllerBase {
  constructor(protected readonly service: ShortcutService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Shortcut })
  async createShortcut(
    @common.Body() data: ShortcutCreateInput
  ): Promise<Shortcut> {
    return await this.service.createShortcut({
      data: {
        ...data,

        appField: data.appField
          ? {
              connect: data.appField,
            }
          : undefined,
      },
      select: {
        appField: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,
        position: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Shortcut] })
  @ApiNestedQuery(ShortcutFindManyArgs)
  async shortcuts(@common.Req() request: Request): Promise<Shortcut[]> {
    const args = plainToClass(ShortcutFindManyArgs, request.query);
    return this.service.shortcuts({
      ...args,
      select: {
        appField: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,
        position: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Shortcut })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async shortcut(
    @common.Param() params: ShortcutWhereUniqueInput
  ): Promise<Shortcut | null> {
    const result = await this.service.shortcut({
      where: params,
      select: {
        appField: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,
        position: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Shortcut })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateShortcut(
    @common.Param() params: ShortcutWhereUniqueInput,
    @common.Body() data: ShortcutUpdateInput
  ): Promise<Shortcut | null> {
    try {
      return await this.service.updateShortcut({
        where: params,
        data: {
          ...data,

          appField: data.appField
            ? {
                connect: data.appField,
              }
            : undefined,
        },
        select: {
          appField: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          id: true,
          position: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Shortcut })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteShortcut(
    @common.Param() params: ShortcutWhereUniqueInput
  ): Promise<Shortcut | null> {
    try {
      return await this.service.deleteShortcut({
        where: params,
        select: {
          appField: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          id: true,
          position: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
